version: '3.8'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportsapp
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: